#!/usr/bin/env python3
import subprocess
import numpy as np
import os
import sys
from scipy.io import loadmat
import json


class FastHenryRunner:
	def __init__(self, fh_exe="FastHenry2/bin/fasthenry"):
		self.fh_exe = fh_exe

	def run(self, inp_file, output_mat="Zc.mat", verbose=True):
		"""
		Run FastHenry on input file.

		Args:
			inp_file: Path to .inp file
			output_mat: Output impedance matrix file (auto-generated by fasthenry)
			verbose: Print execution output

		Returns:
			True if successful, False otherwise
		"""
		if not os.path.exists(inp_file):
			print(f"Error: Input file not found: {inp_file}")
			return False

		cmd = [self.fh_exe, inp_file]
		if verbose:
			print(f"Running: {' '.join(cmd)}")

		try:
			result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
			if verbose:
				print(result.stdout)
			if result.returncode != 0:
				print("Error:", result.stderr)
				return False
			return True
		except subprocess.TimeoutExpired:
			print("Error: Execution timed out")
			return False
		except Exception as e:
			print(f"Error: {e}")
			return False

	def load_zc_matrix(self, mat_file="Zc.mat"):
		"""
		Load impedance matrix from Zc.mat (text format).
		Format: each frequency section with "Impedance matrix for frequency = XXX N x N"
		followed by N lines with N complex values each, where each complex value is "real ±imag j".
		"""
		frequencies = []
		Z_array = []

		with open(mat_file, 'r') as f:
			content = f.read()

		sections = content.split("Impedance matrix for frequency")

		for section in sections[1:]:
			lines = section.strip().split('\n')
			if not lines:
				continue

			first_line = lines[0]
			parts = first_line.split('=')
			if len(parts) < 2:
				continue

			try:
				tokens = parts[1].split()
				freq_str = tokens[0]
				freq = float(freq_str)
				frequencies.append(freq)

				size_str = tokens[1]
				size = int(size_str)

				matrix = []
				data_lines = lines[1:size+1]

				for data_line in data_lines:
					row = []
					tokens = data_line.split()

					j = 0
					while j < len(tokens):
						if j + 1 < len(tokens) and 'j' in tokens[j + 1]:
							try:
								real = float(tokens[j])
								imag_str = tokens[j + 1]
								imag_str = imag_str.replace('j', '')
								imag_str = imag_str.replace('+', '').replace(' ', '')
								imag = float(imag_str)
								val = complex(real, imag)
								row.append(val)
								j += 2
							except ValueError:
								j += 1
						else:
							j += 1

					if len(row) == size:
						matrix.append(row)

				if len(matrix) == size:
					Z_array.append(np.array(matrix, dtype=complex))

			except (ValueError, IndexError):
				pass

		if not frequencies:
			print("No frequency data in Zc.mat")
			return None, None

		if not Z_array:
			print("No impedance matrices found in Zc.mat")
			return None, None

		return np.array(frequencies), np.array(Z_array)

	def extract_inductance(self, freq, Z):
		"""
		Extract self-inductance and mutual inductance from impedance matrix.

		Args:
			freq: Frequency array (Hz)
			Z: Impedance matrix (complex), shape [num_freq, n, n]

		Returns:
			result: Dict with L, M, coupling factor k
		"""
		result = {}

		num_freq = len(freq)
		if Z.ndim == 2:
			Z = Z[np.newaxis, :, :]

		n = Z.shape[1]

		omega = 2 * np.pi * freq
		L = {}

		for i in range(n):
			for j in range(n):
				key = f"L{i}{j}" if i != j else f"L{i}"
				L[key] = np.imag(Z[:, i, j]) / omega

		result["inductance_uh"] = {}
		for key in sorted(L.keys()):
			result["inductance_uh"][key] = L[key] * 1e6

		if n >= 2:
			try:
				k = np.abs(L["L01"]) / np.sqrt(np.abs(L["L0"] * L["L1"]))
				result["coupling_factor"] = k
			except (KeyError, ZeroDivisionError):
				pass

		result["frequencies_hz"] = freq
		result["raw_impedance"] = Z

		return result


def print_results(results):
	"""Pretty-print extracted inductance/mutual inductance."""
	print("\n" + "="*60)
	print("INDUCTANCE EXTRACTION RESULTS")
	print("="*60)

	print("\nFrequencies (Hz):", results["frequencies_hz"])
	print("\nInductances (µH) at each frequency:")

	for key in sorted([k for k in results["inductance_uh"].keys() if "L" in k]):
		values = results["inductance_uh"][key]
		print(f"  {key:4s}: {values}")

	if "coupling_factor" in results:
		print(f"\nCoupling factor k: {results['coupling_factor']}")

	print("="*60 + "\n")


def analytical_straight_wire(length_mm, radius_mm, conductivity=5.8e7):
	"""
	Analytical self-inductance of a straight wire (exterior).

	Formula: L ≈ (μ₀/2π) * l * (ln(l/r) - 2)
	But more practically for a short wire: L ≈ 0.002*l*ln(2*l/d) nH for length l(mm), diameter d(mm)

	Returns inductance in µH
	"""
	mu0 = 4 * np.pi * 1e-7
	length_m = length_mm / 1000
	radius_m = radius_mm / 1000

	L_approx = (mu0 / (2 * np.pi)) * length_m * (np.log(2 * length_m / radius_m) - 2)
	return L_approx * 1e6


def analytical_solenoid(radius_mm, pitch_mm, num_turns, wire_radius_mm):
	"""
	Analytical inductance of a solenoid (Wheeler formula approximation).

	L = (μ₀ * π * r² * n²) / (l * (9*r + 10*l))

	Args:
		radius_mm: Coil radius (mm)
		pitch_mm: Pitch per turn (mm)
		num_turns: Number of turns
		wire_radius_mm: Wire radius (mm)

	Returns inductance in µH
	"""
	mu0 = 4 * np.pi * 1e-7
	radius_m = radius_mm / 1000
	length_m = (pitch_mm * num_turns) / 1000

	numerator = mu0 * np.pi * (radius_m**2) * (num_turns**2)
	denominator = length_m * (9*radius_m + 10*length_m)

	L_wheeler = numerator / denominator
	return L_wheeler * 1e6


if __name__ == "__main__":
	if len(sys.argv) < 2:
		print("Usage: run_fh.py <input.inp> [verbose]")
		sys.exit(1)

	inp_file = sys.argv[1]
	verbose = len(sys.argv) > 2

	runner = FastHenryRunner()
	if runner.run(inp_file, verbose=verbose):
		freq, Z = runner.load_zc_matrix()
		if freq is not None:
			results = runner.extract_inductance(freq, Z)
			print_results(results)
